services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    ports:
      - "3001:3001"

  web:
    build:
      context: ./apps/web
    env_file:
      - ./.env
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  mongo-data:
